version: '3.3'

services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: 'chirper_blade'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: